### PR TITLE
3204425: Verbose error reporting by default

### PR DESCRIPTION
**Pull request by abhisekmazumdar**
Converted the https://www.drupal.org/project/simplytest/issues/3204425 MR.

### CODE REVIEW

**Comment by mglaman** [comment]
I was hoping the update would build the PR

**Comment by abhisekmazumdar** [comment]
> I was hoping the update would build the PR. But I forgot PRs from forks do not get built

Would you like me to create a PR directly from the repository?

**Comment by rachellawson** [comment]
Is there a way for a maintainer to manually kick off a fork on a PR? That would be useful, especially in this scenario

**Comment by mglaman** [comment]
There is not. You can manually make an environment from a branch name only, so I could manually copy it as a branch

**Review by mglaman — APPROVED** [review]
I just verified manually

**Pull request merged**
