### PR TITLE
Unify package.json for project

### PR DESCRIPTION
**Pull request by mglaman**
Moves package.json for React app and theme to project root, alongside
Cypress.

### CODE REVIEW

**Comment by mglaman** [comment]
@rachellawson I'd like to tag you for an eyeball of this. It _should_ help simplify building the React components and theming styling. No more `cd web/...` etc. If you're able to pull down this branch `gh pr checkout 363` and test things look okay, I'd love a +1 before I merge

**Comment by rachellawson** [comment]
looking now…

**Comment by rachellawson** [comment]
hmm - I did a `composer install` all well and good but a `composer compile` led to:

` cd web/themes/simplytest_theme && npm run build

> simplytest-theme@1.0.0 build
> npm run production && npm run postcss


> simplytest-theme@1.0.0 production
> mix --production

sh: mix: command not found`

**Comment by rachellawson** [comment]
ah - I think I see what’s going on here - you want npm to run just from the root folder, not deep in the theme. But the definition in composer.json doesn’t know that.

so, `npm install` followed by `npm run build` successfully builds everything.

**Comment by rachellawson** [comment]
other than changing the line in composer.json, all looks good - the site works well and it builds stuff!!

**Comment by rachellawson** [comment]
I don’t *think* I can commit to others’ PRs atm, otherwise I would

**Comment by mglaman** [comment]
Oh, I didn't realize Composer was trying to run Mix. I'll fix that thanks for testing!

**Pull request merged**
